### ISSUE TITLE
7-10回傳變成標籤

### ISSUE THREAD

**Issue by moumou77130** [letylin/pyptbook#12]
老師您好
想跟老師請問一下
為何回傳的是標籤而不是值
謝謝老師~

![1607670549991](https://user-images.githubusercontent.com/6387546/101967099-58861100-3c55-11eb-9206-9c5b3a883896.jpg)
![1607671796267](https://user-images.githubusercontent.com/6387546/101967148-7b182a00-3c55-11eb-830c-ec6d5de1361d.jpg)

**以下是我html**
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"type="text/css" href="Dom_CSS03.css">
    <script type="text/JavaScript"src="DOM03.js"></script>

</head>

<body>
    <span class="format">存取HTML標籤</span>
    <div class="format">屬性與方法</div>

    <hr>
    
    <ul id="fclass"><li>房地產</li><li>股票</li><li>基金</li></ul>
    <input type="checkbox" name="inv_exper"value="warrant">權證
    <input type="checkbox" name="inv_exper"value="stock">期貨選擇權
    <input type="checkbox" name="inv_exper"value="fund">債卷<br><br>
    <hr>

    <input type="button" onclick="ById()"value="getElementById">
    <input type="button" onclick="ByTagName()"value="getElementsByTagName">
    <input type="button" onclick="ByName()"value="getElementsByName"><br>
    <input type="button" onclick="ByClassName()"value="getElementsByClassName"><br>

    <p id="result"></p>

</body>

</html>

**以下是我JS**
function ById(){
    document.getElementById("result").innerHTML="getElementById()";
         
   }

function ByTagName(){

    var w = document.getElementsByTagName("Li");
    document.getElementById("result").innerHTML=w[2].innerHTML;
         
   }

function ByName(){

    var w = document.getElementsByName("inv_exper")[0].tagName;

    document.getElementById("result").innerHTML=w;
        
   }
function ByClassName(){

    var w= document.getElementsByClassName("format");
    var temp="";
    for(i=0;i<w.length;i++){
        temp+=w[i].tagName+"";
    }
    document.getElementById("result").innerHTML=temp;
         
   }

**Comment by moumou77130** [comment]
> 老師您好
> 想跟老師請問一下
> 為何回傳的是標籤而不是值
> 謝謝老師~
> 
> ![1607670549991](https://user-images.githubusercontent.com/6387546/101967099-58861100-3c55-11eb-9206-9c5b3a883896.jpg)
> ![1607671796267](https://user-images.githubusercontent.com/6387546/101967148-7b182a00-3c55-11eb-830c-ec6d5de1361d.jpg)
> 
> **以下是我html**
> 
> <script type="text/JavaScript"src="DOM03.js"></script> 存取HTML標籤
> 屬性與方法
> ```
> <hr>
> 
> <ul id="fclass"><li>房地產</li><li>股票</li><li>基金</li></ul>
> <input type="checkbox" name="inv_exper"value="warrant">權證
> <input type="checkbox" name="inv_exper"value="stock">期貨選擇權
> <input type="checkbox" name="inv_exper"value="fund">債卷<br><br>
> <hr>
> 
> <input type="button" onclick="ById()"value="getElementById">
> <input type="button" onclick="ByTagName()"value="getElementsByTagName">
> <input type="button" onclick="ByName()"value="getElementsByName"><br>
> <input type="button" onclick="ByClassName()"value="getElementsByClassName"><br>
> 
> 
> <p id="result"></p>
> ```
> 
> **以下是我JS**
> function ById(){
> document.getElementById("result").innerHTML="getElementById()";
> 
> }
> 
> function ByTagName(){
> 
> ```
> var w = document.getElementsByTagName("Li");
> document.getElementById("result").innerHTML=w[2].innerHTML;
> ```
> 
> }
> 
> function ByName(){
> 
> ```
> var w = document.getElementsByName("inv_exper")[0].tagName;
> 
> document.getElementById("result").innerHTML=w;
> ```
> 
> }
> function ByClassName(){
> 
> ```
> var w= document.getElementsByClassName("format");
> var temp="";
> for(i=0;i<w.length;i++){
>     temp+=w[i].tagName+"";
> }
> document.getElementById("result").innerHTML=temp;
> ```
> 
> }

**Comment by letylin** [comment]
這個部分會出現INPUT的結果，根據第 9 列
w = document.getElementsByName("inv_exper")[0].tagName

是以getElementsByName 根據 name 屬性為 inv_exper 的條件，找到所有符合條件的標籤，
並且本範例是回傳找到的第一個的標籤名稱(tagname)，即對應後半段的 [0].tagName

因為第一個找到的標籤對應到書中 E_7_3.html 程式 13 行
<input type="checkbox" name="inv_exper" value="warrant"> 權證

故會回傳標籤名稱是input
故回傳INPUT

希望有回答到您的問題


moumou77130 <notifications@github.com> 於 2020年12月22日 週二 下午6:39寫道：
